<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<footer class="page-footer"><div class="block-footer-bottom"><div class="container">
<div class="main-fix bg-black clearfix">
<div class="row">
<div class="col-lg-3 col-md-3 col-sm-4 col-xs-12">
<div class="collapsible mobile-collapsible">
<h3 class="block-title heading bold">Contact information</h3>
<span class="toggle-tab mobile" style="display: none;"><span class="hidden">hidden</span></span>
<div class="block1 block-content-statick toggle-content">
	<?php 
	    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_contect_information')->toHtml();
	    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
		$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
		$base_url = $storeManager->getStore()->getBaseUrl();
	?>
</div>
</div>
</div>
<div class="col-lg-9 col-md-9 col-sm-8 col-xs-12 clear-both">
<div class="row">
<div class="col-lg-12 row1">
<div class="block-newletter"><div class="testttt">
        <div  class="form subscribe clearfix">
			<div class="block-content">

				<div class="block-title new22">
					<strong>Call for Special Offers</strong>
				</div>
				<div class="field newsletter input-box clearfix">
				    <div class="subscribe-panel">
					<strong style="color:  white;    font-size: 24px;">1-800-997-3077</strong>
				    	<p class="panel-text">or enter email below.</p>
				    </div>
					<div class="visible">
				 		<?php 
				           echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_newsletter')
				               ->toHtml();
						?>
					</div>
				</div>
			</div>
        </div>
</div>
</div>
</div>
<div class="sst">
	<?php 
	    echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_bottom')->toHtml();
	?>
</div>
</div>
</div>
</div>
</div>
</div></div>
<?php if($block->getCopyright() !='') : ?>
<small class="copyright">
<div class="main-row">
    <span><?php /* @escapeNotVerified */ echo $block->getCopyright() ?></span>
</div>
</small>
<?php endif; ?>
</footer>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">



