<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="sections <?php /* @escapeNotVerified */ echo $groupCss ?>">
        <?php $layout = $block->getLayout(); ?>
        <div class="section-items <?php /* @escapeNotVerified */ echo $groupCss ?>-items" data-mage-init='<?php /* @escapeNotVerified */ echo $groupBehavior ?>'>
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="section-item-title <?php /* @escapeNotVerified */ echo $groupCss ?>-item-title" data-role="collapsible">
                    <a class="<?php /* @escapeNotVerified */ echo $groupCss ?>-item-switch" data-toggle="switch" href="#<?php /* @escapeNotVerified */ echo $alias; ?>"><?php /* @escapeNotVerified */ echo $label; ?></a>
                </div>
                <div class="section-item-content <?php /* @escapeNotVerified */ echo $groupCss ?>-item-content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content"><?php /* @escapeNotVerified */ echo $html; ?></div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>




<header class="main_header">
	<div class="top_header">
		<div class="container">
			<ul>
				<li><a href="Javascript:void()">Sign in / Register</a></li>
				<li><a href="Javascript:void()">Special Offers</a></li>
				<li><a href="Javascript:void()">About Us</a></li>
				<li><a href="Javascript:void()" class="top_header_time">8AM - 10PM EST</a></li>
			</ul>
		</div>
	</div>
	<div class="mid_header">
		<div class="container">
			<div class="logo">
				<img src="http://134.209.148.55/hospitalbed/pub/media/header/download.png" alt="" >
			</div>
			<div class="header_mid_inner">
				<ul>
					<li><a href="Javascript:void()">Home</a></li>
					<li><a href="Javascript:void()">Contact Us</a></li>
				</ul>
				<p class="call_us_free">Call us free on 1-800-997-3077</p>
				<p class="unpublished_rates">To hear our unpublished rates</p>
			</div>
			<div class="header_cart">
				<a href="Javascript:void()">
					<span class="cart_icon"><img src="http://134.209.148.55/hospitalbed/pub/media/header/basket_icon.png" alt=""><p class="cart_counting">0</p></span>
					<span class="cart_price">Cart <strong>$0.00</strong></span>
				</a>
			</div>
		</div>
	</div>
	<div class="header_third">
		<div class="container">
			<div class="header_categories">
				<a href="Javascript:void()">
					<span class="categories_hamburg">
						<span></span>
						<span></span>
						<span></span>
					</span>
					<h5>Categories</h5>
				</a>
				<div class="header_categories_dropdown">
					<ul>
						<li>
							<a href="javascript:void()">Mobility Scooters</a>
							<ul class="sub_categories">
								<li><a href="Javascript:void()">3 Wheel Travel Scooter</a></li>
								<li><a href="Javascript:void()">4 Wheel Travel Scooter</a></li>
								<li><a href="Javascript:void()">3 Wheel Mid Size Scooter</a></li>
								<li><a href="Javascript:void()">4 Wheel Mid Size Scooter</a></li>
								<li><a href="Javascript:void()">3 Wheel Full Size Scooter</a></li>
								<li><a href="Javascript:void()">4 Wheel Full Size Scooter</a></li>
								<li><a href="Javascript:void()">Folding Scooters</a></li>
							</ul>
						</li>
						<li><a href="javascript:void()">Hospital Beds</a></li>
						<li><a href="javascript:void()">Power Chairs</a></li>
						<li><a href="javascript:void()">Wheelchairs</a></li>
						<li><a href="javascript:void()">LIFTS & CARRIERS</a></li>
						<li><a href="javascript:void()">Ramps</a></li>
						<li><a href="javascript:void()">Lift Chairs</a></li>
						<li><a href="javascript:void()">Walking Aids</a></li>
						<li class="all_categories_menu"><a href="javascript:void()">All Categories</a></li>
					</ul>
				</div>
			</div>
			<div class="header_search_section">
				<input type="search" name="search" placeholder="Search Here">
				<select>
					<option>All Categories</option>
					<option>Mobility Scooters</option>
					<option>**3 Wheel Travel Scooter</option>
					<option>**4 Wheel Travel Scooter</option>
					<option>**3 Wheel Mid Size Scooter</option>
					<option>**4 Wheel Mid Size Scooter</option>
					<option>**3 Wheel Full Size Scooter</option>
					<option>**4 Wheel Full Size Scooter</option>
				</select>
				<button type="button"><img src="http://134.209.148.55/hospitalbed/pub/media/header/search_icon.png" alt="" ></button>
			</div>
			<div class="live_chat"><a href="javascript:void()"><img src="http://134.209.148.55/hospitalbed/pub/media/header/live_chat_icon.png" alt="" ></a></div>
		</div>
	</div>
</header>















