<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' . $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
$productId = $block->getId();
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$currentproduct = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
echo $currentproduct->getProductUrl();
echo $product->getId();
$product->getId()
?>
<?php if ($title): ?>
    <div class="page-title-wrapper<?php /* @escapeNotVerified */    echo $cssClass; ?>">
        <h1 class="page-title"
            <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */
            echo $block->getId(); ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?php /* @escapeNotVerified */
                echo $block->getAddBaseAttributeAria(); ?>"
            <?php endif; ?>>
            <?php /* @escapeNotVerified */
            echo $title ?>
        </h1>
        <?php echo $block->getChildHtml(); ?>
    </div>
<?php endif; ?>
