<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' . $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
    <div class="page-title-wrapper<?php /* @escapeNotVerified */    echo $cssClass; ?>" >
        <h1 class="page-title"
            <?php if ($block->getId()): ?> id="<?php /* @escapeNotVerified */
            echo $block->getId(); ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()): ?>
                aria-labelledby="<?php /* @escapeNotVerified */
                echo $block->getAddBaseAttributeAria(); ?>"
            <?php endif; ?>>
            <span itemprop="name" >
            <?php /* @escapeNotVerified */
            //echo $title ?>
                </span>
        </h1>
        <?php echo $block->getChildHtml(); ?>
    </div>
<?php endif; ?>

<?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('home_banner')
               ->toHtml();
?>

 <?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('home_category')
               ->toHtml();
?>
<h1 class="home_featured">Featured Products</h1>
<?php 
    echo $block->getLayout()
               ->createBlock('Magento\Cms\Block\Block')
               ->setBlockId('home_product ')
               ->toHtml();
?>

<!--SLIDER END -->


 