<?php
/**
 * Copyright © 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */
$theme = $this->helper('CleverSoft\CleverTheme\Helper\Data');
$logo = '';
$logo_url = '';

$storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();

$headerBuilderHelper = $this->helper('CleverSoft\CleverTheme\Helper\HeaderData');
$settingData = $headerBuilderHelper->getSettingData();

?>
<?php
    if(isset($settingData->logo_mobile->value) && $settingData->logo_mobile->value) {
        $logo = $settingData->logo_mobile->value;
        $logo_url = $headerBuilderHelper->getMediaUrl().$settingData->logo_mobile->value;
    }
?>

<div class="logo-container_mobile d-block <?=isset($settingData->{'_customize_header_logo_mobile_position'}) && $settingData->{'_customize_header_logo_mobile_position'} ? $settingData->{'_customize_header_logo_mobile_position'} : '';?>">
    <?php if($block->isHomePage()):?>
        <strong class="logo">
    <?php else: ?>
        <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
    <?php endif ?>
    <?php if ($logo) { ?>
        <img src="<?php /* @escapeNotVerified */ echo $logo_url ?>"
            title="<?=isset($settingData->{'_customize_logo_mobile_tagline'}) && $settingData->{'_customize_logo_mobile_tagline'} ? $settingData->{'_customize_logo_mobile_tagline'} : 'logo';?>"
            <?=isset($settingData->{'_customize_header_logo_mobile_with'}) && $settingData->{'_customize_header_logo_mobile_with'} ? 'width="'.$settingData->{'_customize_header_logo_mobile_with'}.'"' : '';?>
            alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
        />
    <?php } else {?>
        <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
            title="<?=isset($settingData->{'_customize_logo_mobile_tagline'}) && $settingData->{'_customize_logo_mobile_tagline'} ? $settingData->{'_customize_logo_mobile_tagline'} : 'logo';?>"
            <?=isset($settingData->{'_customize_header_logo_mobile_with'}) && $settingData->{'_customize_header_logo_mobile_with'} ? 'width="'.$settingData->{'_customize_header_logo_mobile_with'}.'"' : '';?>
            alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
            <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
            />
    <?php } ?>
    <?php if($block->isHomePage()):?>
        </strong>
    <?php else:?>
        </a>
    <?php endif?>
    <?php if(isset($settingData->{'_customize_logo_mobile_tagline'}) && $settingData->{'_customize_logo_mobile_tagline'} && isset($settingData->{'_customize-checkbox-logo_mobile-slogan'}) && $settingData->{'_customize-checkbox-logo_mobile-slogan'}):?>
        <p class="logo-tagline"><?=$settingData->{'_customize_logo_mobile_tagline'}?></p>
    <?php endif;?>
</div>