<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
?>
<div class="breadcrumbs"></div>
<?php
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$registry = $objectManager->get('\Magento\Framework\Registry');
$currentProduct = $registry->registry('current_product');
$product = $objectManager->create('Magento\Catalog\Model\Product')->load($currentProduct->getId());
echo '<div class="product_page_below_breadcrumb"><span class="base1" data-ui-id="page-title-wrapper">'.$product->getName().'</span></div>';?>
<div class="columns product_page_main_title">
	<div class="column main">
		<div class="product-info-main">
			<div class="product-reviews-summary empty">
				<div class="reviews-actions">
					<a class="action add" href="<?php echo $product->getProductUrl(); ?>#reviews">Be the first to review this product</a>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/x-magento-init">
        {
            ".breadcrumbs": <?= $viewModel->getJsonConfigurationHtmlEscaped() ?>
        }
</script>
