<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');//get current category
//echo $category->getId();

$_groupCollection = $objectManager->create("\Magento\Eav\Model\ResourceModel\Entity\Attribute\Group\CollectionFactory");

?>
<div class="page-title-wrapper">
    <h1 class="page-title">
        <?php if($category){ ?>
            <span class="base" data-ui-id="page-title-wrapper"><?php echo $category->getName();?></span>
        <?php } ?>
    </h1>
</div>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>

    <?php echo $block->getToolbarHtml(); ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product):

                $fromDate = $_product->getNewsFromDate();
                $toDate = $_product->getNewsToDate();
                //echo $_product->getUpdatedAt();

                $a=$_product->getSpecialPrice();
                $b=$_product->getPrice();
                $x=($a*100)/$b;
                $pecntage=100-$x;
                $percent  = round($pecntage,2);

                // $date1 = "2019/05/22";
                //$date2 = "2019/05/25";
                $date3 = date("Y/m/d");
                $dateTimestamp1 = strtotime($fromDate);
                $dateTimestamp2 = strtotime($toDate);
                $dateTimestamp3 = strtotime($date3);
                $marg = '';
                ?>
                <li class="item product product-item">
                    <?php if($dateTimestamp3>$dateTimestamp1 and $dateTimestamp3<$dateTimestamp2){ ?>
                        <div class="date"> <span class="sticker2 top-right2 "><?php echo "New";?></span> </div>
                    <?php } else{ $marg = 'style="margin-top: 0px;"'; } ?>
                    <?php if ($_product->getSpecialPrice()): ?>
                        <div class="product-label">
                            <span class="sticker top-right" <?php echo $marg;?>><span class="labelsale"><?php echo $percent;?>%</span></span>                            </div>
                    <?php endif; ?>
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $imageDisplayArea);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>

                            <div class="product-specifications">
                                <?php
                                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());

                                var_dump($_product->getAttributeSetId());

                                $groupCollection = $_groupCollection->create();
                                $groupCollection->setAttributeSetFilter($_product->getAttributeSetId());
                                $groupCollection->addFieldToFilter('attribute_group_name', 'Specifications');

                                $groupId = $groupCollection->getFirstItem(); var_dump($groupId);
//
//                                $data=[];
//                                $no =__('No');
//                                foreach ($_product->getAttributes() as $attribute){
//
//                                    if ($attribute->isInGroup($_product->getAttributeSetId(), $groupId) && $attribute->getIsVisibleOnFront() ){
//                                        if($attribute->getFrontend()->getValue($_product) && $attribute->getFrontend()->getValue($_product)!='' && $attribute->getFrontend()->getValue($_product)!=$no){
//                                            $data[]=$attribute;
//                                        }
//                                    }
//
//                                }


                                ?>
<!--                                <table>-->
<!--                                    <tbody>-->
<!--                                    <tr>-->
<!--                                        <td>Weight Capacity:</td>-->
<!--                                        <td>--><?php //echo $weightcapacity; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    <tr>-->
<!--                                        <td>Height Range:</td>-->
<!--                                        <td>--><?php //echo $heightrange; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    <tr>-->
<!--                                        <td>Bed Deck:</td>-->
<!--                                        <td>--><?php //echo $beddeck; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    <tr>-->
<!--                                        <td>Bed Size:</td>-->
<!--                                        <td>--><?php //echo $bedsize; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    <tr>-->
<!--                                        <td>Trendelenburg:</td>-->
<!--                                        <td>--><?php //echo $trendelenburg; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    <tr>-->
<!--                                        <td>Maximum Back Angle:</td>-->
<!--                                        <td>--><?php //echo $maximumbackangle; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    <tr>-->
<!--                                        <td>Warranty:</td>-->
<!--                                        <td>--><?php //echo $warranty; ?><!--</td>-->
<!--                                    </tr>-->
<!--                                    </tbody>-->
<!--                                </table>-->
                            </div>

                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                            <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <?php if ($showDescription):?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                    <div class="product description product-item-description">
                    </div>


                </li>

            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
